import test from 'node:test';
import assert from 'node:assert/strict';
import {freshSave,validateSave,canEnter,restoreRelic,stats,STAGES,SAVE_KEY} from '../js/data/stages.js';
import {Game} from '../js/engine/Game.js';
import {RPGController} from '../js/rpg/RPGController.js';
import {MapManager} from '../js/rpg/MapManager.js';
import {freshCampaign,validateCampaign} from '../js/rpg/SaveManager.js';
import {readFile} from 'node:fs/promises';
const elements=new Map();
function element(id){if(!elements.has(id))elements.set(id,{style:{setProperty(){}},dataset:{},classList:{add(){},remove(){},toggle(){}},open:false,hidden:false,innerHTML:'',textContent:'',addEventListener(){},removeEventListener(){},setAttribute(){},showModal(){this.open=true;},close(){this.open=false;},focus(){}});return elements.get(id);}
const storage=new Map();
globalThis.document={body:element('body'),documentElement:element('html'),getElementById:element,querySelector:s=>element(s),querySelectorAll:()=>[],addEventListener(){}};
globalThis.window={innerWidth:1280,innerHeight:720,addEventListener(){},scrollTo(){}};
globalThis.localStorage={getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)};
globalThis.Image=class {complete=false;naturalWidth=0;};
globalThis.requestAnimationFrame=()=>{};
const ctx=new Proxy({measureText:()=>({width:100}),createLinearGradient:()=>({addColorStop(){}}),createRadialGradient:()=>({addColorStop(){}})},{get:(o,k)=>o[k]||(()=>{})});
const canvas={getContext:()=>ctx,addEventListener(){},focus(){}};
function game(){storage.clear();elements.clear();const g=new Game(canvas);g.toast=()=>{};g.save=freshSave();g.save.started=true;return g;}
function campaignGame(){const g=game(),records=new Map();const saves={save:async(slot,data)=>records.set(slot,validateCampaign(data)),load:async slot=>structuredClone(records.get(slot)),close(){}};const map=new MapManager({fetcher:async url=>({ok:true,json:async()=>JSON.parse(await readFile(new URL('../'+url.replace('./',''),import.meta.url),'utf8'))})});g.rpg=new RPGController(g,{saves,map});g.rpg.fade=async()=>{};g.rpg.prepareArt=async()=>{};const data=freshCampaign('hayeon');data.legacy.started=true;g.rpg.activate(1,data);return g;}
function solve(g){const s=g.stageIndex;const order=s===3?[2,0,1]:g.nodes.map((_,i)=>i);for(const i of order){const n=g.nodes[i];g.player.x=n.x;g.player.y=n.y;g.time=.5;if(s===2)for(let j=0;j<=i;j++)g.interact();else g.interact();}assert.ok(g.nodes.every(n=>n.done));assert.ok(g.boss);}
test('save validation rejects invalid values and prevents skipped progression',()=>{assert.deepEqual(validateSave(null),freshSave());const s=validateSave({version:2,cleared:[0,2,9,'1'],fragments:[-1,1.5,9,Infinity],restored:[107,47],clues:[0,0,99]});assert.deepEqual(s.cleared,[0]);assert.deepEqual(s.fragments,[0,0,9,0,0,0]);assert.deepEqual(s.restored,[100,25,0,0,0,0]);assert.equal(canEnter(s,2),false);assert.equal(canEnter(s,1),true);});
test('restoration consumes correct fragments once and grants permanent stats at 100%',()=>{const s=freshSave();assert.equal(restoreRelic(s,0),false);s.fragments[0]=15;for(let i=0;i<4;i++)assert.equal(restoreRelic(s,0),true);assert.equal(restoreRelic(s,0),false);assert.equal(s.fragments[0],3);assert.deepEqual(stats(s),{hp:115,attack:24});});
test('full six-stage campaign: locked portals, puzzle completion, boss attacks, rewards, save reload and ending',()=>{const g=game();g.enterStage(5);assert.equal(g.state,'title');for(let i=0;i<6;i++){g.enterStage(i);assert.equal(g.state,'battle');assert.equal(g.boss,null);solve(g);g.bossAttack();assert.ok(g.bullets.length>=7);if(i===1)assert.ok(g.hazards.some(h=>h.shape==='cross'));if(i===2)assert.ok(g.hazards.some(h=>h.shape==='ring'));g.boss.hp=0;g.update(.01);assert.equal(g.state,'battle');assert.ok(g.victoryDelay>0);g.update(.81);assert.equal(g.state,'result');assert.ok(g.save.cleared.includes(i));assert.ok(g.save.fragments[i]>=12);assert.ok(g.save.fragments[i]>=STAGES[i].nodes.length+9);const saved=validateSave(JSON.parse(storage.get(SAVE_KEY)));assert.deepEqual(saved.cleared,g.save.cleared);}g.ending();assert.equal(g.state,'ending');assert.match(element('screen').innerHTML,/09:30/);});
test('timing and order puzzles cannot be completed by wrong inputs',()=>{const g=game();g.save.cleared=[0,1,2,3];g.enterStage(0);g.player.x=g.nodes[1].x;g.player.y=g.nodes[1].y;g.time=2;g.interact();assert.equal(g.nodes[1].done,false);g.enterStage(1);g.player.x=g.nodes[2].x;g.player.y=g.nodes[2].y;g.interact();assert.equal(g.nodes[2].done,false);g.enterStage(3);g.player.x=g.nodes[0].x;g.player.y=g.nodes[0].y;g.interact();assert.ok(g.nodes.every(n=>!n.done));g.enterStage(4);g.player.x=g.nodes[0].x;g.player.y=g.nodes[0].y;g.time=2;g.interact();assert.equal(g.nodes[0].done,false);});
test('pause freezes simulation and blocks attack, healing and skills',()=>{const g=game();g.save.cleared=[0];g.enterStage(1);g.dialog('pause');const x=g.player.x,t=g.time;g.keys.add('d');g.player.hp=50;g.attack();g.heal();g.cast(0);g.loop(1000);assert.equal(g.player.x,x);assert.equal(g.time,t);assert.equal(g.player.hp,50);assert.equal(g.bullets.length,0);assert.equal(g.player.shield,0);});
test('shield reflects hostile projectiles; cooldown prevents double casting',()=>{const g=game();g.save.cleared=[0];g.enterStage(1);g.cast(0);g.cast(0);assert.equal(g.cooldowns[0],9);g.bullets=[{x:g.player.x,y:g.player.y,vx:10,vy:0,life:3,ally:false}];g.update(.01);assert.equal(g.bullets[0].ally,true);assert.equal(g.bullets[0].vx,-10);assert.equal(g.player.hp,100);});
test('death grants no run rewards; retry resets combat and heals',()=>{const g=game();g.enterStage(0);g.loot=99;g.player.hp=1;g.damage(5);assert.equal(g.state,'defeat');assert.equal(g.save.fragments[0],0);assert.deepEqual(g.save.cleared,[]);g.enterStage(0);assert.equal(g.loot,0);assert.equal(g.player.hp,100);assert.equal(g.boss,null);});
test('projectiles purify enemies and all stage render paths execute',()=>{const g=game();g.save.cleared=[0,1,2,3,4];for(let i=0;i<6;i++){g.enterStage(i);g.enemies=[{x:g.player.x+1,y:g.player.y-20,hp:10,maxHp:10,speed:0,freeze:0}];g.attack();g.update(.001);assert.equal(g.enemies.length,0);assert.ok(g.drops.length===1||g.loot===1);g.render();}});

test('three primary weapons have distinct volleys and costs',()=>{const g=game();g.enterStage(0);g.enemies=[];for(let i=0;i<3;i++){g.player.shot=0;g.attack();}assert.equal(g.bullets.length,5);g.bullets=[];g.switchWeapon(1);g.player.shot=0;g.attack();assert.equal(g.bullets.length,5);assert.ok(g.bullets.every(b=>b.kind==='petal'));g.bullets=[];g.switchWeapon(2);g.player.shot=0;g.attack();assert.equal(g.bullets.length,1);assert.ok(g.bullets[0].pierce);for(let frame=0;frame<20;frame++)g.update(.03);assert.ok(g.bullets[0].returning);});
test('crescent is directional, clears nearby hostile bullets and respects cooldown',()=>{const g=game();g.enterStage(0);const p=g.player;g.enemies=[{x:p.x+100,y:p.y,hp:200,maxHp:200,freeze:0},{x:p.x-150,y:p.y,hp:200,maxHp:200,freeze:0}];g.bullets=[{x:p.x+80,y:p.y,ally:false}];g.heavyAttack();assert.equal(g.enemies[0].hp,140);assert.equal(g.enemies[1].hp,200);assert.equal(g.bullets.length,0);g.heavyAttack();assert.equal(g.enemies[0].hp,140);});
test('nova requires 50 resonance and cannot repeat during cooldown',()=>{const g=game();g.enterStage(0);g.enemies=[];g.player.focus=49;g.novaAttack();assert.equal(g.player.nova,0);g.player.focus=50;g.novaAttack();assert.equal(g.player.focus,0);assert.equal(g.player.nova,8);g.player.focus=100;g.novaAttack();assert.equal(g.player.focus,100);});
test('pause cancels held touch attack and joystick movement',()=>{const g=game();g.enterStage(0);g.input.attackHeld=true;g.input.vector={x:1,y:0};g.dialog('pause');assert.equal(g.input.attackHeld,false);assert.deepEqual(g.input.vector,{x:0,y:0});});
test('elemental effects select distinct rows for all six stages',()=>{const g=game();for(let i=0;i<6;i++)g.fx.element(i,20,30,'boss',1);assert.deepEqual(g.fx.items.map(e=>e.stage),[0,1,2,3,4,5]);assert.ok(g.fx.items.every(e=>e.size===200&&e.variant===1));g.fx.update(1);assert.equal(g.fx.items.length,0);});
test('enemy atlas and animation rendering execute with loaded image dimensions',()=>{const g=game();g.enterStage(0);for(const [im,w,h]of [[g.sprites.player,1122,1402],[g.sprites.enemies,1024,1536],[g.fx.atlas,1254,1254],[g.fx.elementAtlas,1024,1536]]){im.complete=true;im.naturalWidth=w;im.naturalHeight=h;}for(const state of ['idle','walk','attack','dash','hit']){g.player.moving=state==='walk';g.player.attackAnim=state==='attack'?.3:0;g.player.dashAnim=state==='dash'?.2:0;g.player.hurtAnim=state==='hit'?.2:0;g.fx.element(0,300,300);g.render();}});
test('startup waits for assets and enters lobby, failure gives retry UI',async()=>{const g=game();const images=[g.art,g.background,g.stageArt,g.sprites.player,g.sprites.enemies,g.fx.atlas,g.fx.elementAtlas];images.forEach(i=>i.decode=()=>Promise.resolve());await g.boot();assert.equal(g.state,'lobby');g.art.decode=()=>Promise.reject(new Error('missing art'));await g.boot();assert.equal(g.state,'loading');assert.match(element('screen').innerHTML,/다시 불러오기/);});
test('changing view closes a stale pause dialog',()=>{const g=game();g.enterStage(0);g.pause();assert.equal(element('modal').open,true);g.title();assert.equal(element('modal').open,false);assert.equal(g.state,'title');});

test('RPG room revisit preserves kills, switches, drops, exact player checkpoint and inventory',async()=>{const g=campaignGame();await g.rpg.travel('0-gallery');assert.equal(g.player.maxHp,85);const deadId=g.enemies[0].id;g.enemies[0].hp=0;g.update(.01);assert.ok(g.rpg.data.world.killed.includes(deadId));const sw=g.rpg.area.current.points.find(p=>p.type==='switch');g.player.x=sw.x;g.player.y=sw.y;g.rpg.interact();assert.ok(g.rpg.data.world.switches.includes(sw.id));g.player.x=750;g.player.y=560;g.player.hp=50;g.rpg.data.inventory['archive-0']=1;await g.rpg.save('checkpoint');await g.rpg.travel('0-entry');await g.rpg.travel('0-gallery');assert.ok(!g.enemies.some(e=>e.id===deadId));await g.rpg.load(1);assert.equal(g.player.x,750);assert.equal(g.player.y,560);assert.equal(g.player.hp,50);assert.equal(g.rpg.data.inventory['archive-0'],1);assert.ok(!g.enemies.some(e=>e.id===deadId));g.rpg.dispose();});

test('RPG complete campaign unlocks backtracking archives and quests without replaying dead bosses',async()=>{const g=campaignGame();g.rpg.data.world.choices.approach='comfort';g.rpg.event('talk','jeomdong');for(let stage=0;stage<6;stage++){await g.rpg.travel(`${stage}-gallery`);g.player.inv=100;g.enemies.forEach(e=>e.hp=0);g.update(.01);g.rpg.area.current.points.filter(p=>p.type==='artifact').forEach(p=>g.rpg.recordObservation(p));g.enemies.forEach(e=>e.hp=0);g.update(.01);const sw=g.rpg.area.current.points.find(p=>p.type==='switch');Object.assign(g.player,{x:sw.x,y:sw.y});g.rpg.interact();await g.rpg.travel(`${stage}-sanctum`);solve(g);g.boss.hp=0;g.update(.01);g.update(.81);assert.ok(g.save.cleared.includes(stage));assert.equal(g.rpg.area.current,null);await g.rpg.travel(`${stage}-sanctum`);assert.equal(g.boss,null);assert.ok(g.nodes.every(n=>n.done));await g.rpg.travel(`${stage}-archive`);const chest=g.rpg.area.current.points.find(p=>p.type==='chest');Object.assign(g.player,{x:chest.x,y:chest.y});g.rpg.interact();assert.equal(g.rpg.data.inventory[`archive-${stage}`],1);g.rpg.interact();assert.equal(g.rpg.data.inventory[`archive-${stage}`],1);}g.rpg.data.phase='day';g.rpg.event('talk','jeomdong');assert.equal(Object.values(g.rpg.data.quests).filter(q=>q.done).length,20);await g.rpg.save();g.rpg.dispose();});

test('new game plus resets world and quests while retaining restoration and character',async()=>{const g=campaignGame();g.lobby=()=>{g.state='lobby';};g.save.cleared=[0,1,2,3,4,5];g.save.restored[0]=100;g.save.fragments[0]=9;g.rpg.data.world.killed=['old-monster'];g.rpg.data.inventory['archive-0']=1;g.rpg.data.equipment.charm=0;g.rpg.confirmCycle();await element('confirm-cycle').onclick();assert.equal(g.rpg.data.cycle,2);assert.equal(g.rpg.data.character,'hayeon');assert.equal(g.save.restored[0],100);assert.equal(g.save.fragments[0],9);assert.deepEqual(g.rpg.data.world.killed,[]);assert.deepEqual(g.rpg.data.quests,{});assert.deepEqual(g.save.cleared,[]);await g.rpg.travel('0-gallery');assert.ok(g.enemies[0].maxHp>45);g.rpg.dispose();});
test('museum hub exposes received quests and routes help and saves through settings',()=>{const g=campaignGame();g.rpg.desk();assert.equal(g.state,'hub');assert.match(element('screen').innerHTML,/받은 의뢰/);assert.match(element('screen').innerHTML,/유물 복원대/);element('hub-settings').onclick();assert.match(element('modal-content').innerHTML,/조작법 보기/);g.rpg.dispose();});

test('artifact observations count once, survive room revisit, and render designed exhibit stands',async()=>{const g=campaignGame();await g.rpg.travel('0-gallery');const point=g.rpg.area.current.points.find(p=>p.type==='artifact');assert.equal(g.rpg.recordObservation(point),false);g.enemies.forEach(e=>e.hp=0);g.update(.01);assert.equal(g.rpg.recordObservation(point),true);assert.equal(g.rpg.recordObservation(point),false);await g.rpg.travel('0-entry');await g.rpg.travel('0-gallery');assert.equal(g.rpg.recordObservation(point),false);assert.equal(g.rpg.data.quests['trail-0'].counts.observations,1);g.render();g.rpg.dispose();});
test('touch title opens main lobby once, with a separate reception round trip',async()=>{const g=campaignGame();let entered=0,release;g.display.enter=()=>{entered++;return new Promise(resolve=>release=resolve);};g.rpg.mainLobby.splash();assert.equal(g.state,'splash');assert.match(element('screen').innerHTML,/화면을 터치하면 시작합니다\./);const first=element('touch-start').onclick();await g.rpg.mainLobby.enter();assert.equal(entered,1);release();await first;assert.equal(g.state,'main-lobby');assert.match(element('screen').innerHTML,/복원 파편/);element('main-desk').onclick();assert.equal(g.state,'hub');element('desk-main-back').onclick();assert.equal(g.state,'main-lobby');g.rpg.dispose();});
test('main lobby uses each curator illustration while battle keeps animated sprites',()=>{const g=campaignGame();for(const id of ['sion','hayeon']){g.rpg.data.character=id;g.rpg.mainLobby.render();assert.match(element('screen').innerHTML,new RegExp(id+'-lobby-portrait.png'));assert.doesNotMatch(element('screen').innerHTML,/main-hero-sprite/);assert.equal(g.rpg.character.art,id==='sion'?'sion-animation.png':'hayeon-animation.png');}g.rpg.dispose();});

test('exhibit reconstruction follows kills, blocks early inspection and completes only on record',async()=>{const g=campaignGame();await g.rpg.travel('0-gallery');const r=g.rpg,p=r.area.current.points.find(p=>p.type==='artifact');assert.equal(r.restorationProgress(p),0);assert.equal(r.inspectArtifact(p),false);g.enemies[0].hp=0;g.update(.01);assert.ok(r.restorationProgress(p)>0);assert.ok(r.restorationProgress(p)<.88);g.enemies.forEach(e=>e.hp=0);g.update(.01);assert.equal(r.restorationProgress(p),.88);assert.equal(r.inspectArtifact(p),true);assert.equal(r.restorationProgress(p),.88);g.closeDialog();assert.equal(r.recordObservation(p),true);assert.equal(r.restorationProgress(p),1);await r.travel('0-entry');await r.travel('0-gallery');assert.equal(r.restorationProgress(p),1);r.dispose();});
test('projectiles pass exhibit positions but remain blocked by real walls',async()=>{const g=campaignGame();await g.rpg.travel('0-gallery');for(const p of g.rpg.area.current.points.filter(p=>p.type==='artifact'))assert.equal(g.rpg.projectileBlocked(p.x-30,p.y-20,p.x+30,p.y-20),false);assert.equal(g.rpg.projectileBlocked(380,320,460,320),true);assert.equal(g.rpg.projectileBlocked(260,195,300,195),false);g.rpg.dispose();});
