import test from 'node:test';
import assert from 'node:assert/strict';
import {joystickVector,canvasPoint,movementVector,TouchInput} from '../js/platform/TouchInput.js';
import {MobileDisplay} from '../js/platform/MobileDisplay.js';
import {animationFrame,segmentDistance} from '../js/data/combat.js';
const nodes=new Map();
function node(id){if(!nodes.has(id))nodes.set(id,{open:false,hidden:true,style:{},dataset:{},capture:new Set(),events:{},classList:{toggle(){},remove(){}},addEventListener(type,fn){this.events[type]=fn;},getBoundingClientRect(){return{left:0,top:0,width:134,height:134};},setPointerCapture(id){this.capture.add(id);},hasPointerCapture(id){return this.capture.has(id);},releasePointerCapture(id){this.capture.delete(id);},showModal(){this.open=true;},close(){this.open=false;}});return nodes.get(id);}
function setup(){nodes.clear();globalThis.document={getElementById:node,querySelectorAll:()=>[],body:node('body'),documentElement:node('html'),addEventListener(){}};globalThis.window={innerWidth:844,innerHeight:390,matchMedia:()=>({matches:false}),addEventListener(){}};globalThis.screen={orientation:{addEventListener(){}}};const game={state:'battle',keys:new Set(),firing:false,attack(){this.attacks=(this.attacks||0)+1;},title(){this.state='title';}};game.input=new TouchInput(game);game.input.setMode('touch');game.display=new MobileDisplay(game);return game;}
const event=(id,x=120,y=67)=>({pointerId:id,clientX:x,clientY:y,preventDefault(){}});
test('joystick deadzone and clamping preserve analog strength',()=>{assert.deepEqual(joystickVector(1,1),{x:0,y:0});assert.equal(joystickVector(26,0).x,.5);assert.equal(joystickVector(300,0).x,1);assert.ok(Math.abs(Math.hypot(...Object.values(joystickVector(90,90)))-1)<1e-9);assert.deepEqual(movementVector(new Set(),{x:.3,y:0}),{x:.3,y:0});assert.ok(Math.abs(Math.hypot(...Object.values(movementVector(new Set(['w','d']))))-1)<1e-9);});
test('letterboxed screen coordinates align with canvas',()=>{const p=canvasPoint({left:0,top:0,width:844,height:390},422,195);assert.ok(Math.abs(p.x-640)<1e-9);assert.equal(p.y,360);assert.equal(canvasPoint({left:0,top:0,width:844,height:390},0,195).x,0);});
test('releasing joystick does not release a second finger holding attack',()=>{const g=setup();g.input.beginJoystick(event(1));node('touch-attack').events.pointerdown(event(2));assert.equal(g.input.attackHeld,true);g.input.endJoystick(event(1));assert.deepEqual(g.input.vector,{x:0,y:0});assert.equal(g.input.attackHeld,true);node('touch-attack').events.pointerup(event(1));assert.equal(g.input.attackHeld,true);node('touch-attack').events.pointerup(event(2));assert.equal(g.input.attackHeld,false);assert.equal(g.attacks,1);});
test('joystick pointer ownership rejects a second finger and resets on cancellation',()=>{const g=setup();g.input.beginJoystick(event(3));g.input.beginJoystick(event(4,0));assert.equal(g.input.joyPointer,3);g.input.endJoystick(event(4));assert.equal(g.input.joyPointer,3);g.input.endJoystick(event(3));assert.equal(g.input.joyPointer,null);assert.deepEqual(g.input.vector,{x:0,y:0});});
test('pause/reset releases all captures and prevents stuck input',()=>{const g=setup();g.input.beginJoystick(event(7));node('touch-attack').events.pointerdown(event(8));g.input.reset();assert.equal(g.input.attackHeld,false);assert.equal(g.input.joyPointer,null);assert.equal(node('joystick').capture.size,0);assert.equal(node('touch-attack').capture.size,0);});
test('portrait guard blocks simulation while preserving existing pause dialog',()=>{const g=setup();g.display.active=true;node('modal').open=true;window.innerWidth=390;window.innerHeight=844;g.keys.add('w');g.display.sync();assert.equal(g.display.blocked,true);assert.equal(node('rotate-notice').open,true);assert.equal(g.keys.size,0);window.innerWidth=844;window.innerHeight=390;g.display.sync();assert.equal(g.display.blocked,false);assert.equal(node('rotate-notice').open,false);assert.equal(node('modal').open,true);});
test('denied fullscreen/orientation gracefully falls back to rotate notice',async()=>{const g=setup();window.innerWidth=390;window.innerHeight=844;document.documentElement.requestFullscreen=async()=>{throw new Error('denied');};screen.orientation.lock=async()=>{throw new Error('unsupported');};await g.display.enter();assert.equal(g.display.locked,false);assert.equal(g.display.blocked,true);assert.equal(node('rotate-notice').open,true);});
test('animation rows and swept projectile collision are deterministic',()=>{assert.deepEqual(animationFrame('walk',.2),{row:1,frame:2});assert.deepEqual(animationFrame('hit',.39),{row:4,frame:3});assert.deepEqual(animationFrame('dash',.01),{row:3,frame:0});assert.equal(segmentDistance(50,0,0,0,100,0),0);assert.equal(segmentDistance(50,30,0,0,100,0),30);});
