import {STAGES} from '../data/stages.js';
import {gateOpen} from '../rpg/AreaManager.js';
export class ExhibitionRenderer {
 constructor(){this.atlas=new Image();this.atlas.src='./assets/exhibition-props-transparent.png';}
 sprite(c,index,x,y,width,height){if(!this.atlas.complete||!this.atlas.naturalWidth)return false;const sw=this.atlas.naturalWidth/4,sh=this.atlas.naturalHeight/3,trim=index===6||index===7?.9:1;c.drawImage(this.atlas,index%4*sw,Math.floor(index/4)*sh,sw,sh*trim,x,y,width,height*trim);return true;}
 cabinet(c,stage,x,y,{width=108,lit=true,locked=false,label='',sub=''}={}){const h=width*1.15;c.save();c.fillStyle='#090d2555';c.beginPath();c.ellipse(x,y+12,width*.42,13,0,0,Math.PI*2);c.fill();c.globalAlpha=lit?1:.72;if(!this.sprite(c,stage+6,x-width/2,y-h+20,width,h)){c.fillStyle='#3b3040';c.fillRect(x-width*.35,y-30,width*.7,45);c.strokeStyle='#d4bd8b';c.strokeRect(x-width*.35,y-h+25,width*.7,h-50);c.fillStyle='#91d9ed22';c.fillRect(x-width*.35,y-h+25,width*.7,h-50);}if(lit&&!locked){c.strokeStyle=STAGES[stage].color+'aa';c.lineWidth=2;c.beginPath();c.ellipse(x,y+14,width*.36,9,0,0,Math.PI*2);c.stroke();}if(locked){c.fillStyle='#111829df';c.fillRect(x-22,y-60,44,21);c.fillStyle='#eab9b2';c.font='11px sans-serif';c.textAlign='center';c.fillText('잠김',x,y-45);}c.globalAlpha=1;c.textAlign='center';if(label){c.font='13px sans-serif';const w=Math.min(250,c.measureText(label).width+16);c.fillStyle='#121a2bdf';c.fillRect(x-w/2,y+22,w,22);c.fillStyle='#f1dfb9';c.fillText(label,x,y+37);}if(sub){c.font='11px sans-serif';c.fillStyle='#b9d8db';c.fillText(sub,x,y+59);}c.restore();}
 node(c,node,index,stage,time){this.cabinet(c,stage,node.x,node.y,{lit:node.done,width:112,label:node.name,sub:node.done?'전시 복원 완료':stage===2?`감상 방향 ${node.turn} → ${index+1}`:'유물 전시대 · E / 조사'});if((stage===0&&index===1||stage===4)&&!node.done){c.fillStyle=Math.sin(time*2)>=0?'#8df0c3':'#ed96a2';c.beginPath();c.arc(node.x,node.y-103,6,0,Math.PI*2);c.fill();}}
 wall(c,stage,x,y){if(this.sprite(c,stage,x-7,y-31,54,77))return;c.save();const gradient=c.createLinearGradient(x,y-13,x,y+40);gradient.addColorStop(0,STAGES[stage].color);gradient.addColorStop(1,'#202438');c.fillStyle=gradient;c.fillRect(x,y-8,40,48);this.sprite(c,stage,x-7,y-31,54,77);c.restore();}
 room(c,room,data,time){for(let y=5;y<16;y++)for(let x=2;x<30;x++)if(room.tiles[y][x]==='1')this.wall(c,room.stage,x*40,y*40);for(const p of room.points){const locked=!gateOpen(p.gate,data),done=data.world.switches.includes(p.id)||data.world.collected.includes(p.id);if(p.type==='npc'){c.save();c.fillStyle='#b9dbed';c.font='28px Georgia';c.textAlign='center';c.fillText('✧',p.x,p.y-25);c.font='13px sans-serif';c.fillText(p.name,p.x,p.y+25);c.restore();continue;}const stage=p.type==='portal'&&/^[0-5]-/.test(p.target)?Number(p.target[0]):room.stage;const sub=locked?(p.gate.ability!==undefined?STAGES[p.gate.ability].skill+' 필요':'전시 조명 복구 필요'):p.type==='portal'?'전시대 조사 → 구역 이동':p.type==='artifact'?(done?'관찰 기록 완료':'유물 관찰 · E / 조사'):p.type==='checkpoint'?'휴식 · 자동 저장':done?'기록 완료':'E / 조사';this.cabinet(c,p.type==='switch'||p.type==='checkpoint'?5:stage,p.x,p.y,{width:p.type==='portal'?98:90,locked,lit:!locked,label:p.name,sub});}}
}
