import {STAGES} from '../data/stages.js';
import {gateOpen} from '../rpg/AreaManager.js';
export class ExhibitionRenderer {
 constructor(){this.atlas=new Image();this.atlas.src='./assets/exhibition-props-transparent.png';this.assembly=new Map();this.openAtlas=new Image();this.openAtlas.src='./assets/exhibition-open.png';}
 sprite(c,index,x,y,width,height){const atlas=index>=6?this.openAtlas:this.atlas;if(!atlas.complete||!atlas.naturalWidth)return false;const sw=atlas.naturalWidth/4,sh=atlas.naturalHeight/3,trim=1;c.drawImage(atlas,index%4*sw,Math.floor(index/4)*sh,sw,sh*trim,x,y,width,height*trim);return true;}
 cabinet(c,stage,x,y,{width=90,lit=true,locked=false,label='',sub='',progress=1,time=0,key=''}={}){const h=width*1.15;c.save();c.fillStyle='#090d2555';c.beginPath();c.ellipse(x,y+12,width*.42,13,0,0,Math.PI*2);c.fill();c.globalAlpha=lit?1:.72;if(!(key?this.assemble(c,stage+6,x-width/2,y-h+20,width,h,progress,time,key):this.sprite(c,stage+6,x-width/2,y-h+20,width,h))){c.fillStyle='#3b3040';c.fillRect(x-width*.35,y-30,width*.7,45);c.fillStyle='#b88b59';c.beginPath();c.ellipse(x,y-42,width*.18,24,0,0,Math.PI*2);c.fill();}if(lit&&!locked){c.strokeStyle=STAGES[stage].color+'aa';c.lineWidth=2;c.beginPath();c.ellipse(x,y+14,width*.36,9,0,0,Math.PI*2);c.stroke();}if(locked){c.fillStyle='#111829df';c.fillRect(x-22,y-60,44,21);c.fillStyle='#eab9b2';c.font='11px sans-serif';c.textAlign='center';c.fillText('잠김',x,y-45);}c.globalAlpha=1;c.textAlign='center';if(label){c.font='13px sans-serif';const w=Math.min(250,c.measureText(label).width+16);c.fillStyle='#121a2bdf';c.fillRect(x-w/2,y+22,w,22);c.fillStyle='#f1dfb9';c.fillText(label,x,y+37);}if(sub){c.font='11px sans-serif';c.fillStyle='#b9d8db';c.fillText(sub,x,y+59);}c.restore();}
 node(c,node,index,stage,time){this.cabinet(c,stage,node.x,node.y,{lit:node.done,width:112,label:node.name,sub:node.done?'전시 복원 완료':stage===2?`감상 방향 ${node.turn} → ${index+1}`:'유물 전시대 · E / 조사'});if((stage===0&&index===1||stage===4)&&!node.done){c.fillStyle=Math.sin(time*2)>=0?'#8df0c3':'#ed96a2';c.beginPath();c.arc(node.x,node.y-103,6,0,Math.PI*2);c.fill();}}
 assemble(c,index,x,y,w,h,target,time,key){
  if(!this.openAtlas.complete||!this.openAtlas.naturalWidth)return false;
  let a=this.assembly.get(key);if(!a){a={value:target,time,burst:-99};this.assembly.set(key,a);}const dt=Math.max(0,Math.min(.1,time-a.time));a.time=time;
  if(target>a.value+.005)a.burst=time;a.value+= (target-a.value)*(1-Math.exp(-dt*5));if(Math.abs(target-a.value)<.001)a.value=target;
  const sw=this.openAtlas.naturalWidth/4,sh=this.openAtlas.naturalHeight/3,sx=index%4*sw,sy=Math.floor(index/4)*sh,gap=(1-a.value)*19;
  for(let row=0;row<3;row++)for(let col=0;col<2;col++){const dx=(col-.5)*gap,dy=(row-1)*gap*.55;c.save();c.globalAlpha*=.65+.35*a.value;c.drawImage(this.openAtlas,sx+col*sw/2,sy+row*sh/3,sw/2,sh/3,x+col*w/2+dx,y+row*h/3+dy+Math.sin(time*2+row+col)*gap*.08,w/2,h/3);c.restore();}
  if(time-a.burst<.9){c.save();c.strokeStyle=target===1?'#ffe3a0':'#a9dcfa';c.globalAlpha*=1-(time-a.burst)/.9;c.lineWidth=2;c.beginPath();c.ellipse(x+w/2,y+h-8,w*(.3+(time-a.burst)*.2),10+(time-a.burst)*14,0,0,Math.PI*2);c.stroke();c.restore();}return true;
 }
 wall(c,stage,x,y){if(this.sprite(c,stage,x-7,y-31,54,77))return;c.save();const gradient=c.createLinearGradient(x,y-13,x,y+40);gradient.addColorStop(0,STAGES[stage].color);gradient.addColorStop(1,'#202438');c.fillStyle=gradient;c.fillRect(x,y-8,40,48);this.sprite(c,stage,x-7,y-31,54,77);c.restore();}
 room(c,room,data,time,progress=()=>1){if(this.roomId!==room.id){this.roomId=room.id;this.assembly.clear();}for(let y=5;y<16;y++)for(let x=2;x<30;x++)if(room.tiles[y][x]==='1')this.wall(c,room.stage,x*40,y*40);for(const p of room.points){const locked=!gateOpen(p.gate,data),done=data.world.switches.includes(p.id)||data.world.collected.includes(p.id);if(p.type==='npc'){c.save();c.fillStyle='#b9dbed';c.font='28px Georgia';c.textAlign='center';c.fillText('✧',p.x,p.y-25);c.font='13px sans-serif';c.fillText(p.name,p.x,p.y+25);c.restore();continue;}const stage=p.type==='portal'&&/^[0-5]-/.test(p.target)?Number(p.target[0]):room.stage;const sub=locked?(p.gate.ability!==undefined?STAGES[p.gate.ability].skill+' 필요':'전시 조명 복구 필요'):p.type==='portal'?'전시대 조사 → 구역 이동':p.type==='artifact'?(done?'유물 복원 완료':progress(p)<.88?'적 정화 중 · 복원 '+Math.round(progress(p)*100)+'%':'정화 완료 · 조사로 복원 마무리'):p.type==='checkpoint'?'휴식 · 자동 저장':done?'기록 완료':'E / 조사';this.cabinet(c,p.type==='switch'||p.type==='checkpoint'?5:stage,p.x,p.y,{width:p.type==='portal'?86:78,locked,lit:!locked,label:p.name,sub,...(p.type==='artifact'?{progress:progress(p),time,key:p.id}:{})});}}
}
