export function validateRoom(room,id){if(!room||room.id!==id||room.tileSize!==40||room.tiles.length!==18||room.tiles.some(row=>typeof row!=='string'||row.length!==32||/[^01]/.test(row))||!room.spawns?.default||!Array.isArray(room.points))throw new Error('타일맵 형식 오류: '+id);return room;}
export class MapManager {
 constructor({fetcher=(...args)=>globalThis.fetch(...args),limit=4}={}){this.fetcher=fetcher;this.limit=limit;this.cache=new Map();}
 async load(id,signal){if(!/^[0-5]-(entry|gallery|archive|sanctum)$/.test(id))throw new Error('알 수 없는 구역입니다.');if(this.cache.has(id)){const room=this.cache.get(id);this.cache.delete(id);this.cache.set(id,room);return structuredClone(room);}const response=await this.fetcher(`./data/maps/${id}.json`,{signal});if(!response.ok)throw new Error('맵을 불러오지 못했습니다: '+id);const room=validateRoom(await response.json(),id);this.cache.set(id,room);while(this.cache.size>this.limit)this.cache.delete(this.cache.keys().next().value);return structuredClone(room);}
 blocked(room,x,y,radius=15){return [[x-radius,y-radius],[x+radius,y-radius],[x-radius,y+radius],[x+radius,y+radius]].some(([px,py])=>room.tiles[Math.floor(py/40)]?.[Math.floor(px/40)]!=='0');}
 move(room,player,dx,dy){const count=Math.max(1,Math.ceil(Math.hypot(dx,dy)/8));for(let i=0;i<count;i++){if(!this.blocked(room,player.x+dx/count,player.y))player.x+=dx/count;if(!this.blocked(room,player.x,player.y+dy/count))player.y+=dy/count;}}
 rayBlocked(room,x1,y1,x2,y2){const count=Math.max(1,Math.ceil(Math.hypot(x2-x1,y2-y1)/8));for(let i=1;i<=count;i++)if(this.blocked(room,x1+(x2-x1)*i/count,y1+(y2-y1)*i/count,0))return true;return false;}
 nextStep(room,actor,target){const start=[Math.floor(actor.x/40),Math.floor(actor.y/40)],goal=[Math.floor(target.x/40),Math.floor(target.y/40)],key=(x,y)=>y*32+x;const queue=[start],previous=new Map([[key(...start),null]]);let found=false;for(let i=0;i<queue.length;i++){const [x,y]=queue[i];if(x===goal[0]&&y===goal[1]){found=true;break;}for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){const nx=x+dx,ny=y+dy,k=key(nx,ny);if(room.tiles[ny]?.[nx]==='0'&&!previous.has(k)){previous.set(k,key(x,y));queue.push([nx,ny]);}}}if(!found)return actor;let node=key(...goal),root=key(...start);if(node===root)return target;while(previous.get(node)!==root&&previous.get(node)!==null)node=previous.get(node);return {x:node%32*40+20,y:Math.floor(node/32)*40+20};}
 clear(){this.cache.clear();}
}
